kind: Deployment
apiVersion: apps/v1
metadata:
  name: lms-user-web
  namespace: lms-cmmty-dev
  labels:
    k8s-app: lms-user-web
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: lms-user-web
  template:
    metadata:
      labels:
        k8s-app: lms-user-web
    spec:
      containers:
        - name: lms-user-web
          image: >-
            070976870339.dkr.ecr.ap-northeast-2.amazonaws.com/lms-cmmty-user-web:devel-a7bc671
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1G
            requests:
              cpu: 250m
              memory: 500M

---

kind: Service
apiVersion: v1
metadata:
  name: lms-user-web
  namespace: lms-cmmty-dev
  labels:
    k8s-app: lms-user-web
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    k8s-app: lms-user-web

---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: lms-user-web-ingress
  namespace: lms-cmmty-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
spec:
  tls:
    - hosts:
        - www.dev.urbanlt.co.kr
      secretName: www.dev.urbanlt.co.kr
  rules:
    - host: www.dev.urbanlt.co.kr
      http:
        paths:
          - path: /
            backend:
              serviceName: lms-user-web
              servicePort: 80